/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"

#import "Types.h"
#import "Errors.h"

enum EDAMSponsoredGroupRole {
  SponsoredGroupRole_GROUP_MEMBER = 1,
  SponsoredGroupRole_GROUP_ADMIN = 2,
  SponsoredGroupRole_GROUP_OWNER = 3
};

@interface EDAMPublicUserInfo : NSObject <NSCoding> {
  EDAMUserID __userId;
  NSString * __shardId;
  int __privilege;
  NSString * __username;
  NSString * __noteStoreUrl;

  BOOL __userId_isset;
  BOOL __shardId_isset;
  BOOL __privilege_isset;
  BOOL __username_isset;
  BOOL __noteStoreUrl_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=userId, setter=setUserId:) EDAMUserID userId;
@property (nonatomic, retain, getter=shardId, setter=setShardId:) NSString * shardId;
@property (nonatomic, getter=privilege, setter=setPrivilege:) int privilege;
@property (nonatomic, retain, getter=username, setter=setUsername:) NSString * username;
@property (nonatomic, retain, getter=noteStoreUrl, setter=setNoteStoreUrl:) NSString * noteStoreUrl;
#endif

- (id) initWithUserId: (EDAMUserID) userId shardId: (NSString *) shardId privilege: (int) privilege username: (NSString *) username noteStoreUrl: (NSString *) noteStoreUrl;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (EDAMUserID) userId;
- (void) setUserId: (EDAMUserID) userId;
- (BOOL) userIdIsSet;

- (NSString *) shardId;
- (void) setShardId: (NSString *) shardId;
- (BOOL) shardIdIsSet;

- (int) privilege;
- (void) setPrivilege: (int) privilege;
- (BOOL) privilegeIsSet;

- (NSString *) username;
- (void) setUsername: (NSString *) username;
- (BOOL) usernameIsSet;

- (NSString *) noteStoreUrl;
- (void) setNoteStoreUrl: (NSString *) noteStoreUrl;
- (BOOL) noteStoreUrlIsSet;

@end

@interface EDAMPremiumInfo : NSObject <NSCoding> {
  EDAMTimestamp __currentTime;
  BOOL __premium;
  BOOL __premiumRecurring;
  EDAMTimestamp __premiumExpirationDate;
  BOOL __premiumExtendable;
  BOOL __premiumPending;
  BOOL __premiumCancellationPending;
  BOOL __canPurchaseUploadAllowance;
  NSString * __sponsoredGroupName;
  int __sponsoredGroupRole;

  BOOL __currentTime_isset;
  BOOL __premium_isset;
  BOOL __premiumRecurring_isset;
  BOOL __premiumExpirationDate_isset;
  BOOL __premiumExtendable_isset;
  BOOL __premiumPending_isset;
  BOOL __premiumCancellationPending_isset;
  BOOL __canPurchaseUploadAllowance_isset;
  BOOL __sponsoredGroupName_isset;
  BOOL __sponsoredGroupRole_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=currentTime, setter=setCurrentTime:) EDAMTimestamp currentTime;
@property (nonatomic, getter=premium, setter=setPremium:) BOOL premium;
@property (nonatomic, getter=premiumRecurring, setter=setPremiumRecurring:) BOOL premiumRecurring;
@property (nonatomic, getter=premiumExpirationDate, setter=setPremiumExpirationDate:) EDAMTimestamp premiumExpirationDate;
@property (nonatomic, getter=premiumExtendable, setter=setPremiumExtendable:) BOOL premiumExtendable;
@property (nonatomic, getter=premiumPending, setter=setPremiumPending:) BOOL premiumPending;
@property (nonatomic, getter=premiumCancellationPending, setter=setPremiumCancellationPending:) BOOL premiumCancellationPending;
@property (nonatomic, getter=canPurchaseUploadAllowance, setter=setCanPurchaseUploadAllowance:) BOOL canPurchaseUploadAllowance;
@property (nonatomic, retain, getter=sponsoredGroupName, setter=setSponsoredGroupName:) NSString * sponsoredGroupName;
@property (nonatomic, getter=sponsoredGroupRole, setter=setSponsoredGroupRole:) int sponsoredGroupRole;
#endif

- (id) initWithCurrentTime: (EDAMTimestamp) currentTime premium: (BOOL) premium premiumRecurring: (BOOL) premiumRecurring premiumExpirationDate: (EDAMTimestamp) premiumExpirationDate premiumExtendable: (BOOL) premiumExtendable premiumPending: (BOOL) premiumPending premiumCancellationPending: (BOOL) premiumCancellationPending canPurchaseUploadAllowance: (BOOL) canPurchaseUploadAllowance sponsoredGroupName: (NSString *) sponsoredGroupName sponsoredGroupRole: (int) sponsoredGroupRole;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (EDAMTimestamp) currentTime;
- (void) setCurrentTime: (EDAMTimestamp) currentTime;
- (BOOL) currentTimeIsSet;

- (BOOL) premium;
- (void) setPremium: (BOOL) premium;
- (BOOL) premiumIsSet;

- (BOOL) premiumRecurring;
- (void) setPremiumRecurring: (BOOL) premiumRecurring;
- (BOOL) premiumRecurringIsSet;

- (EDAMTimestamp) premiumExpirationDate;
- (void) setPremiumExpirationDate: (EDAMTimestamp) premiumExpirationDate;
- (BOOL) premiumExpirationDateIsSet;

- (BOOL) premiumExtendable;
- (void) setPremiumExtendable: (BOOL) premiumExtendable;
- (BOOL) premiumExtendableIsSet;

- (BOOL) premiumPending;
- (void) setPremiumPending: (BOOL) premiumPending;
- (BOOL) premiumPendingIsSet;

- (BOOL) premiumCancellationPending;
- (void) setPremiumCancellationPending: (BOOL) premiumCancellationPending;
- (BOOL) premiumCancellationPendingIsSet;

- (BOOL) canPurchaseUploadAllowance;
- (void) setCanPurchaseUploadAllowance: (BOOL) canPurchaseUploadAllowance;
- (BOOL) canPurchaseUploadAllowanceIsSet;

- (NSString *) sponsoredGroupName;
- (void) setSponsoredGroupName: (NSString *) sponsoredGroupName;
- (BOOL) sponsoredGroupNameIsSet;

- (int) sponsoredGroupRole;
- (void) setSponsoredGroupRole: (int) sponsoredGroupRole;
- (BOOL) sponsoredGroupRoleIsSet;

@end

@interface EDAMAuthenticationResult : NSObject <NSCoding> {
  EDAMTimestamp __currentTime;
  NSString * __authenticationToken;
  EDAMTimestamp __expiration;
  EDAMUser * __user;
  EDAMPublicUserInfo * __publicUserInfo;
  NSString * __noteStoreUrl;
  NSString * __webApiUrlPrefix;

  BOOL __currentTime_isset;
  BOOL __authenticationToken_isset;
  BOOL __expiration_isset;
  BOOL __user_isset;
  BOOL __publicUserInfo_isset;
  BOOL __noteStoreUrl_isset;
  BOOL __webApiUrlPrefix_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=currentTime, setter=setCurrentTime:) EDAMTimestamp currentTime;
@property (nonatomic, retain, getter=authenticationToken, setter=setAuthenticationToken:) NSString * authenticationToken;
@property (nonatomic, getter=expiration, setter=setExpiration:) EDAMTimestamp expiration;
@property (nonatomic, retain, getter=user, setter=setUser:) EDAMUser * user;
@property (nonatomic, retain, getter=publicUserInfo, setter=setPublicUserInfo:) EDAMPublicUserInfo * publicUserInfo;
@property (nonatomic, retain, getter=noteStoreUrl, setter=setNoteStoreUrl:) NSString * noteStoreUrl;
@property (nonatomic, retain, getter=webApiUrlPrefix, setter=setWebApiUrlPrefix:) NSString * webApiUrlPrefix;
#endif

- (id) initWithCurrentTime: (EDAMTimestamp) currentTime authenticationToken: (NSString *) authenticationToken expiration: (EDAMTimestamp) expiration user: (EDAMUser *) user publicUserInfo: (EDAMPublicUserInfo *) publicUserInfo noteStoreUrl: (NSString *) noteStoreUrl webApiUrlPrefix: (NSString *) webApiUrlPrefix;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (EDAMTimestamp) currentTime;
- (void) setCurrentTime: (EDAMTimestamp) currentTime;
- (BOOL) currentTimeIsSet;

- (NSString *) authenticationToken;
- (void) setAuthenticationToken: (NSString *) authenticationToken;
- (BOOL) authenticationTokenIsSet;

- (EDAMTimestamp) expiration;
- (void) setExpiration: (EDAMTimestamp) expiration;
- (BOOL) expirationIsSet;

- (EDAMUser *) user;
- (void) setUser: (EDAMUser *) user;
- (BOOL) userIsSet;

- (EDAMPublicUserInfo *) publicUserInfo;
- (void) setPublicUserInfo: (EDAMPublicUserInfo *) publicUserInfo;
- (BOOL) publicUserInfoIsSet;

- (NSString *) noteStoreUrl;
- (void) setNoteStoreUrl: (NSString *) noteStoreUrl;
- (BOOL) noteStoreUrlIsSet;

- (NSString *) webApiUrlPrefix;
- (void) setWebApiUrlPrefix: (NSString *) webApiUrlPrefix;
- (BOOL) webApiUrlPrefixIsSet;

@end

@interface EDAMBootstrapProfile : NSObject <NSCoding> {
  NSString * __name;
  BOOL __preferred;
  NSDictionary * __settings;

  BOOL __name_isset;
  BOOL __preferred_isset;
  BOOL __settings_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, getter=preferred, setter=setPreferred:) BOOL preferred;
@property (nonatomic, retain, getter=settings, setter=setSettings:) NSDictionary * settings;
#endif

- (id) initWithName: (NSString *) name preferred: (BOOL) preferred settings: (NSDictionary *) settings;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSString *) name;
- (void) setName: (NSString *) name;
- (BOOL) nameIsSet;

- (BOOL) preferred;
- (void) setPreferred: (BOOL) preferred;
- (BOOL) preferredIsSet;

- (NSDictionary *) settings;
- (void) setSettings: (NSDictionary *) settings;
- (BOOL) settingsIsSet;

@end

@interface EDAMBootstrapInfo : NSObject <NSCoding> {
  NSArray * __profiles;

  BOOL __profiles_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=profiles, setter=setProfiles:) NSArray * profiles;
#endif

- (id) initWithProfiles: (NSArray *) profiles;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSArray *) profiles;
- (void) setProfiles: (NSArray *) profiles;
- (BOOL) profilesIsSet;

@end

@protocol EDAMUserStore <NSObject>
- (BOOL) checkVersion: (NSString *) clientName : (int16_t) edamVersionMajor : (int16_t) edamVersionMinor;  // throws TException
- (EDAMBootstrapInfo *) getBootstrapInfo: (NSString *) locale;  // throws TException
- (EDAMAuthenticationResult *) authenticate: (NSString *) username : (NSString *) password : (NSString *) consumerKey : (NSString *) consumerSecret;  // throws EDAMUserException *, EDAMSystemException *, TException
- (EDAMAuthenticationResult *) refreshAuthentication: (NSString *) authenticationToken;  // throws EDAMUserException *, EDAMSystemException *, TException
- (EDAMUser *) getUser: (NSString *) authenticationToken;  // throws EDAMUserException *, EDAMSystemException *, TException
- (EDAMPublicUserInfo *) getPublicUserInfo: (NSString *) username;  // throws EDAMNotFoundException *, EDAMSystemException *, EDAMUserException *, TException
- (EDAMPremiumInfo *) getPremiumInfo: (NSString *) authenticationToken;  // throws EDAMUserException *, EDAMSystemException *, TException
- (NSString *) getNoteStoreUrl: (NSString *) authenticationToken;  // throws EDAMUserException *, EDAMSystemException *, TException
@end

@interface EDAMUserStoreClient : NSObject <EDAMUserStore> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface EDAMUserStoreProcessor : NSObject <TProcessor> {
  id <EDAMUserStore> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithUserStore: (id <EDAMUserStore>) service;
- (id<EDAMUserStore>) service;
@end

@interface EDAMUserStoreConstants : NSObject {
}
+ (int16_t) EDAM_VERSION_MAJOR;
+ (int16_t) EDAM_VERSION_MINOR;
@end
